services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      POSTGRES_URI: postgres://some_user:some_password@db:5432/some_database?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:17
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: some_database
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d some_database -U some_user" ]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
volumes:
  db:
    driver: local
