// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// DefaultErrorResponse defines model for DefaultErrorResponse.
type DefaultErrorResponse struct {
	// Error error description
	Error string `json:"error"`
}

// ProductListGetResponse defines model for ProductListGetResponse.
type ProductListGetResponse = []ProductListGetResponseItem

// ProductListGetResponseItem defines model for ProductListGetResponseItem.
type ProductListGetResponseItem struct {
	// DiscountedPrice Product discounted price
	DiscountedPrice int `json:"discountedPrice"`

	// Id id of product
	Id string `json:"id"`

	// Image Product image
	Image string `json:"image"`

	// Name Product name
	Name string `json:"name"`

	// OriginalPrice Product original price
	OriginalPrice int `json:"originalPrice"`

	// Rating Product rating
	Rating int `json:"rating"`
}

// OptionalPageParam defines model for OptionalPageParam.
type OptionalPageParam = int

// ProductListGetParams defines parameters for ProductListGet.
type ProductListGetParams struct {
	// Page paginate result
	Page *OptionalPageParam `form:"page,omitempty" json:"page,omitempty" validate:"omitempty,gt=0"`
}
